common:
  img_topic: "/alphasense_driver_ros/cam0"
  lid_topic: "/os_cloud_node/points"
  imu_topic: "/alphasense_driver_ros/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib: # Lidar-to-IMU
  extrinsic_T: [-0.037, -0.008, -0.026] 
  extrinsic_R: [1, 0, 0, 0, -1, 0, 0, 0, -1]

  # CAM to LiDAR
  Rcl: [ 0.00343924,  -0.00100547,   1.00001724,
          0.99999964,   0.00601285,   0.00344522, 
           -0.00601642,   0.99998142,   0.00098474,]
  Pcl: [   0.08622284 , 0.05557528, 0.01659839 ]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  hilti_en: true
  point_filter_num: 1
  filter_size_surf: 0.1 # 0.2
  lidar_type: 3 # Ouster
  scan_line: 16
  blind: 1.0 # 0.1 0.3
 
vio:
  max_iterations: 5
  outlier_threshold: 500
  img_point_cov: 1000
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.1
  gyr_cov: 0.01
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0001 # 0.0025
  voxel_size: 0.4
  max_layer: 2
  max_points_num: 100
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "exp09_cupola"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
